package algs.blog.searching.gperf;

import algs.blog.searching.search.ICollectionSearch;

/* C code produced by gperf version 3.0.3 */
/* Command-line: ./src/gperf ../two.keys  */
/* Computed positions: -k'1-4,6-9' */
/* Converted to Java by George Heineman. .*/
public class GPerfTwo implements ICollectionSearch<String> {

	
	public static final int TOTAL_KEYWORDS = 641;
	public static final int MIN_WORD_LENGTH = 2;
	public static final int MAX_WORD_LENGTH = 21;
	public static final int MIN_HASH_VALUE = 2;
	public static final int MAX_HASH_VALUE = 4412;
	
	/* maximum key range = 4411, duplicates = 0 */

	static short asso_values[] =
	    {
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413,    0,   30,   35,
	        15,    5,  560,  435,  170,   20,  449,  825,    0,  285,
	        75,  120, 1015,  877,  295,  160,   40,  860,  927,  781,
	       215,  945, 1429,   10, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413,
	      4413, 4413, 4413, 4413, 4413, 4413, 4413, 4413
	    };
	
	static char bytes[] = new char[9];
	static int hash (String str) {
	  int hval = str.length();
	  str.getChars(0, (hval < 9) ? hval : 9, bytes, 0);
	  switch (hval)
	    {
	      default:
	        hval += asso_values[bytes[8]];
	      /*FALLTHROUGH*/
	      case 8:
	        hval += asso_values[bytes[7]];
	      /*FALLTHROUGH*/
	      case 7:
	        hval += asso_values[bytes[6]];
	      /*FALLTHROUGH*/
	      case 6:
	        hval += asso_values[bytes[5]];
	      /*FALLTHROUGH*/
	      case 5:
	      case 4:
	        hval += asso_values[bytes[3]];
	      /*FALLTHROUGH*/
	      case 3:
	        hval += asso_values[bytes[2]+2];
	      /*FALLTHROUGH*/
	      case 2:
	        hval += asso_values[bytes[1]];
	      /*FALLTHROUGH*/
	      case 1:
	        hval += asso_values[bytes[0]];
	        break;
	    }
	  return hval;
	}

	static String wordlist[] =
	    {
	      null, null,
	      "aa",
	      null, null, null, null,
	      "ea",
	      null, null, null, null, null, null, null, null,
	      "elcaja",
	      "da",
	      null, null, null,
	      "labara",
	      null, null,
	      "lija",
	      null, null,
	      "labella",
	      null, null, null, null,
	      "ba",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null,
	      "labba",
	      "dacite",
	      null, null, null,
	      "dabih",
	      "cabala",
	      null, null, null, null, null, null, null,
	      "dabb",
	      null, null,
	      "tabella",
	      "baa",
	      null,
	      "cabda",
	      null, null, null,
	      "labellate",
	      null, null,
	      "na",
	      "taa",
	      "naja",
	      null,
	      "caraja",
	      null, null, null, null,
	      "babbie",
	      "earlobe",
	      "labiatae",
	      "nace",
	      "tabby",
	      null, null,
	      "abbadide",
	      null,
	      "nable",
	      null, null,
	      "tabarded",
	      "naga",
	      "aalii",
	      "ababua",
	      null,
	      "labefact",
	      null,
	      "abaca",
	      null, null,
	      "labefactation",
	      null, null, null,
	      "cabalic",
	      "naa",
	      null,
	      "laang",
	      null, null, null, null, null, null,
	      "iacchic",
	      null, null,
	      "nabby",
	      null, null, null, null, null,
	      "balija",
	      null, null, null, null, null, null, null, null, null,
	      "bacillicide",
	      null, null,
	      "cabaletta",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "daboya",
	      "tabacin",
	      null, null, null, null, null,
	      "nabalite",
	      null, null,
	      "tabefaction",
	      null, null, null, null,
	      "oarage",
	      null, null, null,
	      "iambe",
	      "cabaho",
	      null, null,
	      "saba",
	      "lache",
	      null,
	      "obclude",
	      null,
	      "labelloid",
	      null,
	      "sabeca",
	      null, null, null, null, null, null, null, null,
	      "dacha",
	      "habena",
	      null,
	      "saa",
	      "nama",
	      null, null, null, null,
	      "sabadilla",
	      null, null,
	      "babasco",
	      null, null, null, null, null, null,
	      "nabalitic",
	      "iambically",
	      null, null, null, null,
	      "habbe",
	      null, null, null, null, null,
	      "habble",
	      "earache",
	      null, null, null, null, null,
	      "aaronite",
	      null, null, null,
	      "nabaloi",
	      null,
	      "haab",
	      null, null, null, null, null, null,
	      "abacination",
	      "babiche",
	      null, null, null,
	      "abasgi",
	      "tabitha",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "objectative",
	      null, null, null,
	      "naght",
	      null, null, null, null, null, null,
	      "ababdeh",
	      null, null, null, null,
	      "baalath",
	      "sabadine",
	      null, null, null, null, null, null,
	      "earthslide",
	      null, null,
	      "taalbond",
	      null, null,
	      "macaca",
	      "ra",
	      null,
	      "raja",
	      null, null, null, null,
	      "maba",
	      null, null,
	      "abacist",
	      null,
	      "raya",
	      null, null, null,
	      "babehood",
	      null,
	      "habilitate",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "daceloninae",
	      null, null,
	      "habitance",
	      null,
	      "raband",
	      null, null,
	      "rabi",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "iacchos",
	      null,
	      "raad",
	      "hache",
	      null, null, null, null,
	      "abama",
	      "sacerdotage",
	      "daalder",
	      "caballer",
	      "caam",
	      "caama",
	      null,
	      "rabatte",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "napa",
	      null, null,
	      "iambist",
	      null,
	      "lactamide",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "sabaoth",
	      null,
	      "tabetless",
	      null, null, null, null, null, null, null,
	      "baalish",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      "rabbin",
	      null,
	      "sabbitha",
	      null, null, null, null, null, null,
	      "eaglestone",
	      null, null, null, null, null, null,
	      "oakesia",
	      null,
	      "eagerness",
	      "sabaeanism",
	      null, null, null, null,
	      "sabbathaic",
	      "sabbathlike",
	      null, null, null, null,
	      "oaklet",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "machi",
	      null,
	      "gabelle",
	      "macanese",
	      null, null, null,
	      "xerarch",
	      null,
	      "rafe",
	      "rache",
	      "labrys",
	      null, null,
	      "rabbinica",
	      "jacami",
	      null,
	      "rabbinically",
	      null, null,
	      "gabby",
	      "oafish",
	      null, null, null, null, null, null,
	      "habanera",
	      null,
	      "raash",
	      null, null, null, null,
	      "cabalassou",
	      "garawi",
	      null, null, null, null, null, null, null,
	      "mabellona",
	      null,
	      "baetyl",
	      null, null,
	      "habenaria",
	      "jabbed",
	      null,
	      "dacryon",
	      "cabestro",
	      null, null, null, null,
	      "cabalism",
	      "naassenes",
	      null, null, null, null, null, null, null, null,
	      "baalshem",
	      null, null, null,
	      "jabarite",
	      null,
	      "labdacism",
	      null, null, null, null,
	      "haberdash",
	      null,
	      "haberdasher",
	      null, null, null, null,
	      "gabion",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "fa",
	      "nabalism",
	      null,
	      "jaalin",
	      "abastardize",
	      null, null, null, null, null, null, null,
	      "gabionade",
	      null, null, null, null,
	      "faba",
	      null, null, null,
	      "laborage",
	      null,
	      "fabes",
	      null,
	      "fabella",
	      "obe",
	      "jabot",
	      null, null, null,
	      "fabaceae",
	      null, null,
	      "oafdom",
	      null,
	      "dabbling",
	      null,
	      "dabblingly",
	      null, null, null,
	      "fiji",
	      null, null,
	      "iachimo",
	      null,
	      "maam",
	      null,
	      "earful",
	      null, null, null,
	      "babblingly",
	      null, null, null, null, null, null, null, null,
	      "maamselle",
	      null, null,
	      "martext",
	      "caatinga",
	      "dacoitage",
	      "abaff",
	      null, null, null, null,
	      "jabers",
	      null, null, null, null, null, null, null, null,
	      "facepiece",
	      "macadamite",
	      null, null, null, null, null, null, null, null, null,
	      "babblesome",
	      null,
	      "dactylorhiza",
	      null, null, null, null, null,
	      "gabbroic",
	      "eachwhere",
	      "saccharoceptive",
	      null, null, null, null, null, null, null, null,
	      "fableland",
	      null, null,
	      "dabblingness",
	      null,
	      "jaboticaba",
	      null, null, null, null, null,
	      "oadal",
	      null, null,
	      "rabbiter",
	      "facticide",
	      null, null, null, null, null, null, null,
	      "jacinthe",
	      null, null, null, null, null,
	      "jaborandi",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "laborsome",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "babongo",
	      null, null, null,
	      "ecchondroma",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "aardwolf",
	      null, null, null, null, null,
	      "daff",
	      null, null, null, null, null,
	      "gabelleman",
	      null, null, null, null, null, null, null,
	      "macaasim",
	      null, null, null, null, null, null,
	      "caffa",
	      "laager",
	      null,
	      "baahling",
	      null, null, null, null, null, null, null,
	      "gabber",
	      null, null, null, null, null, null,
	      "saccharoscope",
	      null, null,
	      "icerya",
	      "saccharamide",
	      null, null,
	      "wace",
	      null,
	      "gabbard",
	      "earnings",
	      null, null, null, null,
	      "abarambo",
	      null, null, null,
	      "wabena",
	      null,
	      "macaranga",
	      null, null, null, null, null,
	      "flaxy",
	      null, null, null, null, null, null, null, null, null,
	      "iamatology",
	      null,
	      "ka",
	      null, null, null,
	      "wabby",
	      null, null,
	      "habergeon",
	      null, null,
	      "wabble",
	      null, null, null, null, null, null,
	      "rabbindom",
	      null,
	      "xeriff",
	      null, null, null,
	      "kabel",
	      null, null, null,
	      "habronema",
	      "waac",
	      null, null, null,
	      "rada",
	      "gabblement",
	      "kabard",
	      null, null, null, null, null, null,
	      "lacelike",
	      "madi",
	      null, null,
	      "caaming",
	      null, null, null, null,
	      "galactoscope",
	      null, null,
	      "uayeb",
	      "caback",
	      "wagaun",
	      null,
	      "eaglelike",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null,
	      "iao",
	      null, null,
	      "daydawn",
	      "haff",
	      null, null,
	      "cacatua",
	      "babelike",
	      "cablelike",
	      "babua",
	      null,
	      "earlock",
	      null,
	      "tablelike",
	      null,
	      "cabuya",
	      null, null, null,
	      "rabblesome",
	      null,
	      "oakling",
	      null, null, null, null,
	      "nagaika",
	      null, null, null,
	      "qere",
	      null, null, null, null, null, null,
	      "ajaja",
	      null, null, null, null, null, null, null,
	      "ullage",
	      "ya",
	      null, null, null, null, null,
	      "dabchick",
	      "yaje",
	      "yacal",
	      null, null, null,
	      "kabardian",
	      null, null,
	      "ehuawa",
	      "tabitude",
	      "yaba",
	      "kabob",
	      null, null, null, null,
	      "wafd",
	      "labefy",
	      null, null, null, null,
	      "fabricative",
	      null, null, null,
	      "kamba",
	      "waasi",
	      "eagerly",
	      "ubbenite",
	      null, null, null, null, null,
	      "yagi",
	      "yacca",
	      null, null, null,
	      "gabionage",
	      null,
	      "wafty",
	      "abave",
	      null,
	      "kafa",
	      null,
	      "yabble",
	      null,
	      "fabledom",
	      null,
	      "hacky",
	      null,
	      "lacerative",
	      null,
	      "iiwi",
	      null,
	      "tabefy",
	      null, null,
	      "vaalite",
	      null, null, null, null,
	      "macrodome",
	      null,
	      "madhva",
	      "eatability",
	      "ean",
	      "tactive",
	      "mabinogion",
	      "pacaya",
	      null, null, null,
	      "paced",
	      "pacate",
	      null, null,
	      "paba",
	      null, null, null, null,
	      "aani",
	      null,
	      "sabuja",
	      null, null, null, null, null, null, null, null, null,
	      "vaccicide",
	      null, null,
	      "paal",
	      null, null,
	      "gabrielrache",
	      null, null,
	      "tabaniform",
	      "facsimilize",
	      "oarcock",
	      null,
	      "kavi",
	      null, null, null,
	      "tableity",
	      null,
	      "eaglewood",
	      "pabble",
	      "babblative",
	      "intext",
	      null, null, null, null,
	      "tabanuco",
	      null, null,
	      "kachin",
	      "sabanut",
	      null, null, null, null,
	      "iacchus",
	      null, null, null, null, null,
	      "habitude",
	      null, null,
	      "habitualize",
	      null,
	      "abdominoscope",
	      null, null, null, null, null, null, null, null,
	      "vache",
	      null, null, null, null, null, null, null, null, null,
	      "nabalus",
	      null, null, null, null,
	      "caapeba",
	      null, null, null, null,
	      "wabber",
	      null, null, null, null, null,
	      "icecraft",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "fabianism",
	      null, null, null, null, null,
	      "lambsdown",
	      null, null, null, null,
	      "vacation",
	      null,
	      "vacational",
	      null, null, null, null, null,
	      "ebullioscope",
	      "vacantheartedness",
	      null, null,
	      "labarum",
	      "vagabondage",
	      null, null, null, null, null, null, null, null, null,
	      "ianthina",
	      null, null, null, null,
	      "aardvark",
	      "hadji",
	      null, null, null, null, null, null,
	      "maharaja",
	      null, null, null,
	      "pacht",
	      null, null,
	      "kababish",
	      null, null, null,
	      "habitative",
	      null, null, null, null,
	      "tabacum",
	      null, null,
	      "vaalpens",
	      null,
	      "acyloxy",
	      null, null, null, null,
	      "gabfest",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "machinofacture",
	      null, null,
	      "iraqi",
	      null, null,
	      "rabbitlike",
	      "kakapo",
	      null, null, null,
	      "ianthinite",
	      null,
	      "oaklike",
	      null, null, null, null,
	      "waggie",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "earlship",
	      null, null,
	      "obispo",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "takyr",
	      null, null, null, null,
	      "gadolinite",
	      null, null, null, null, null, null, null, null, null,
	      "vaccaria",
	      "yabber",
	      null, null,
	      "daijo",
	      null, null, null, null, null, null, null, null,
	      "fabiform",
	      null, null,
	      "pakawa",
	      null,
	      "sacktime",
	      "gablelike",
	      null, null, null, null,
	      "takedown",
	      null,
	      "dacryagogue",
	      "gablock",
	      null, null,
	      "sabathikos",
	      null, null,
	      "xanthate",
	      null, null,
	      "dactylopore",
	      "icelike",
	      "jabbering",
	      "jabul",
	      "jabberingly",
	      null, null, null, null, null, null,
	      "abhiseka",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "yachtist",
	      "ijo",
	      null, null, null, null, null, null, null, null,
	      "habendum",
	      null, null,
	      "waddy",
	      "pabouch",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "xanthian",
	      null,
	      "xanthaline",
	      null,
	      "cachexy",
	      null, null, null, null, null, null, null, null,
	      "vaccinotherapy",
	      null,
	      "vagrantlike",
	      null, null, null, null, null, null,
	      "facks",
	      null, null, null, null, null, null,
	      "kabonga",
	      null,
	      "babbittry",
	      null, null, null, null, null, null,
	      "narrative",
	      null,
	      "achomawi",
	      null,
	      "oariopathy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "ideative",
	      "za",
	      "macduff",
	      "oafishly",
	      null, null, null,
	      "wichtje",
	      null, null, null, null, null, null, null, null,
	      "xanthelasma",
	      null, null, null,
	      "xanthelasmoidea",
	      null, null, null, null,
	      "zabeta",
	      "paccanarist",
	      "earmuff",
	      "kadarite",
	      null,
	      "xanthation",
	      null, null,
	      "nabobery",
	      null, null,
	      "qoph",
	      null,
	      "xenarchi",
	      null,
	      "dermatauxe",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "zacatec",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "kadikane",
	      "sabbatary",
	      "zabtie",
	      null, null,
	      "labialize",
	      null, null, null, null, null, null, null,
	      "baalize",
	      "naebody",
	      null, null, null,
	      "yadava",
	      null, null,
	      "yade",
	      null, null, null, null, null, null, null, null, null,
	      "hemiataxy",
	      null,
	      "zabaean",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "yachtdom",
	      null,
	      "pachyacria",
	      null, null,
	      "jambalaya",
	      "facedown",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "raddlings",
	      null, null, null, null, null, null, null, null, null,
	      "oariotomy",
	      null, null, null, null,
	      "zambo",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "padda",
	      "dacryocystorhinostomy",
	      null,
	      "saccomys",
	      null,
	      "xanthamide",
	      null,
	      "zacateco",
	      null, null, null, null, null, null, null, null,
	      "iambize",
	      null, null,
	      "tachytomy",
	      null, null, null,
	      "dacryops",
	      "xanthamic",
	      null,
	      "echimys",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "nephrauxe",
	      "sabdariffa",
	      "zacaton",
	      null,
	      "macabresque",
	      null, null, null, null, null, null, null,
	      "cachaza",
	      null, null, null, null, null,
	      "yachtmanship",
	      "yachtsmanlike",
	      null, null, null, null,
	      "yachting",
	      "backshift",
	      "hadendowa",
	      "haemorrhage",
	      "wabuma",
	      "naphthyl",
	      null, null, null, null, null,
	      "zabaglione",
	      null, null, null, null,
	      "qoheleth",
	      "kadmi",
	      null, null, null,
	      "yaff",
	      null, null, null, null, null,
	      "zachun",
	      null, null, null,
	      "xenophobe",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "udi",
	      "vaagmer",
	      null, null,
	      "laparohysteropexy",
	      null, null, null, null, null, null, null,
	      "xanthoderm",
	      null, null,
	      "ubi",
	      null, null, null, null, null, null, null,
	      "kabuli",
	      null, null,
	      "fabaceous",
	      null, null, null, null, null,
	      "jabberwock",
	      "jabberwocky",
	      null,
	      "jabberwockian",
	      "ubii",
	      null,
	      "zaberma",
	      null, null,
	      "zabra",
	      null, null, null, null, null, null,
	      "iatrochemistry",
	      null,
	      "gaincome",
	      null, null, null, null, null, null, null, null, null,
	      "qasida",
	      null, null, null, null, null, null, null, null,
	      "daiva",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "fabulosity",
	      null,
	      "qubba",
	      null, null,
	      "labiograph",
	      null, null, null, null, null, null, null, null, null,
	      "pachyderma",
	      null,
	      "uaraycu",
	      null, null, null, null, null,
	      "uglisome",
	      "cawk",
	      null, null, null,
	      "walleye",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "nakedize",
	      null,
	      "oaktongue",
	      "yagua",
	      null, null,
	      "ebullitive",
	      "quachil",
	      null,
	      "waapa",
	      null, null, null, null, null, null, null,
	      "backdown",
	      null, null, null, null, null, null, null, null,
	      "jacutinga",
	      null, null, null, null, null,
	      "fabrikoid",
	      null, null, null, null, null, null, null,
	      "ulcerative",
	      null, null, null, null, null, null,
	      "sabbathize",
	      null,
	      "radiative",
	      null,
	      "rabbinize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "quadratics",
	      null, null, null,
	      "zabaism",
	      null, null,
	      "jacamerops",
	      null, null, null,
	      "xanthochroism",
	      "ganja",
	      null, null, null, null, null, null, null, null,
	      "takhtadjy",
	      null,
	      "paauw",
	      null, null, null,
	      "vacancy",
	      null, null, null, null, null,
	      "vacantly",
	      null,
	      "iambographer",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "jinja",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "acenaphthenyl",
	      null,
	      "pacemaking",
	      null, null, null,
	      "valeryl",
	      null, null, null, null, null, null, null, null,
	      "sallowy",
	      null,
	      "tachograph",
	      null, null,
	      "macklike",
	      null, null, null, null,
	      "oakberry",
	      null,
	      "pacative",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "felichthys",
	      "oaty",
	      null,
	      "fairtime",
	      null, null,
	      "kabirpanthi",
	      null,
	      "habutaye",
	      null, null,
	      "yarpha",
	      null,
	      "backrope",
	      null, null, null, null, null,
	      "ubication",
	      "padge",
	      null, null, null, null, null, null,
	      "gallify",
	      "gadabout",
	      null, null,
	      "obelize",
	      null, null, null,
	      "quadrans",
	      "ulotrichi",
	      null, null,
	      "macadamize",
	      "macadamizer",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "jackshaft",
	      null, null, null, null, null, null, null, null, null,
	      "fackings",
	      null, null,
	      "yachty",
	      null, null, null, null, null, null, null, null,
	      "pabulation",
	      null, null, null,
	      "yamp",
	      "yampa",
	      null, null, null,
	      "vacuome",
	      null, null, null,
	      "kalidium",
	      "vacatur",
	      null, null, null,
	      "wabunga",
	      null, null,
	      "enterauxe",
	      null, null, null, null, null,
	      "waldgrave",
	      null, null,
	      "kabbeljaws",
	      null, null, null, null, null, null,
	      "gaffkya",
	      null, null, null, null,
	      "haemaspectroscope",
	      null, null, null, null,
	      "cacoepy",
	      "jacobinize",
	      null, null, null, null, null,
	      "markdown",
	      null, null,
	      "uji",
	      "quadriderivative",
	      null,
	      "cabreuva",
	      null, null,
	      "narrowy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      "xanthorrhiza",
	      null, null,
	      "quackish",
	      null,
	      "quackishly",
	      "viewy",
	      null, null, null, null, null, null, null, null, null,
	      "wadlike",
	      null, null, null, null, null,
	      "ziffs",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "xanthidium",
	      null, null, null, null,
	      "zephyr",
	      null, null, null, null, null, null, null,
	      "naturecraft",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "vacantry",
	      null,
	      "xanthyl",
	      null, null,
	      "rachigraph",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null,
	      "quackhood",
	      null, null, null, null, null, null, null,
	      "kadu",
	      "quadriga",
	      null, null,
	      "qintar",
	      null, null, null, null, null,
	      "ouija",
	      null, null, null, null, null, null,
	      "vasotribe",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "omentopexy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      "udderlike",
	      "zaitha",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "jaculative",
	      null, null,
	      "uang",
	      null,
	      "kanauji",
	      "quadragenarious",
	      "rabulous",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "iatraliptics",
	      null, null,
	      "vaginopexy",
	      null, null,
	      "ichnography",
	      null, null,
	      "yaghourt",
	      "pagoscope",
	      "macrograph",
	      "uglify",
	      null,
	      "jawy",
	      null, null, null, null,
	      "bandboxy",
	      null,
	      "kabaragoya",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null,
	      "gaelicize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "xanthocyanopy",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "oatfowl",
	      null, null,
	      "kaffeeklatsch",
	      "quadragesima",
	      "jackanapish",
	      "waddywood",
	      null,
	      "daddocky",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "taeniafuge",
	      null, null,
	      "taxy",
	      null, null, null, null,
	      "zimbabwe",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      "ebionize",
	      null, null, null, null, null, null, null,
	      "paddlelike",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "wagonwright",
	      "zande",
	      null,
	      "wasandawi",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      "oceanways",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "saarbrucken",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null,
	      "rectopexy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null,
	      "machopolyp",
	      null, null, null, null, null, null, null,
	      "quawk",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "quarterstaff",
	      null, null, null, null, null,
	      "abiotrophy",
	      null, null, null, null, null, null,
	      "zandmole",
	      null, null,
	      "zapupe",
	      null, null, null,
	      "zavijava",
	      null, null, null,
	      "zebralike",
	      "ponja",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "gainstrive",
	      null, null, null, null, null, null,
	      "wagnerize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "uberous",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "uaupe",
	      null, null, null, null, null, null, null,
	      "tabularize",
	      null, null,
	      "faithworthy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "ultraorthodoxy",
	      null,
	      "ultrashrewd",
	      null, null,
	      "zadruga",
	      null, null, null, null,
	      "uberousness",
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "xenagogy",
	      null, null, null,
	      "gastrohysteropexy",
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "quacky",
	      null, null, null,
	      "iconograph",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null,
	      "ichthyopsida",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "quashy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "quacksalver",
	      null,
	      "salpingopexy",
	      null,
	      "yawp",
	      null, null,
	      "paeanize",
	      null,
	      "ferrotype",
	      null, null,
	      "ubiquarian",
	      null, null, null, null, null,
	      "vaishnava",
	      null, null,
	      "kataplexy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null,
	      "unagonize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "ubiquitary",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null,
	      "waferwork",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      "packstaff",
	      null, null, null, null,
	      "quillaja",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "rainbowy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null,
	      "quinisext",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null,
	      "pabulary",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "kaolinize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "yaguaza",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null,
	      "vacuefy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null,
	      "panmixy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null,
	      "xanthophyll",
	      null, null, null, null, null, null, null, null,
	      "vacuumize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null,
	      "obstupefy",
	      null, null, null, null, null, null, null, null, null,
	      "uberously",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "zootaxy",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null,
	      "quimbaya",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null,
	      "quakerize",
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null, null, null, null, null, null, null, null,
	      null, null,
	      "ukiyoye"
	    };

	@Override
	public boolean exists(String target) {
		int len = target.length();
		if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
	    {
	      int key = hash (target);

	      if (key <= MAX_HASH_VALUE && key >= 0)
	        {
	          String s = wordlist[key];

	          if (s != null && s.charAt(0) == target.charAt(0) && s.equals(target)) {
	        	  return true;
	          }
	        }
	    }
		
	  return false;
	}

	
}
